# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-21 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('kode_kabupaten', models.CharField(db_column='kode_kabupaten', max_length=20, verbose_name='Kode Kabupaten')),
                ('nama_kabupaten', models.CharField(db_column='nama_kabupaten', max_length=200, verbose_name='Nama Kabupaten')),
            ],
            options={
                'db_table': 'kabupaten',
                'verbose_name': 'Kabupaten',
                'verbose_name_plural': 'Kabupaten',
            },
        ),
        migrations.CreateModel(
            name='LokasiBidang',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('kode_lokasi_bidang', models.CharField(db_column='kode_lokasi_bidang', max_length=20, verbose_name='Kode Lokasi Bidang')),
                ('nama_lokasi_bidang', models.CharField(db_column='nama_lokasi_bidang', max_length=200, verbose_name='Nama Lokasi Bidang')),
                ('id_kabupaten', models.ForeignKey(db_column='id_kabupaten', on_delete=django.db.models.deletion.CASCADE, to='sppd.Kabupaten', verbose_name='Kabupaten')),
            ],
            options={
                'db_table': 'lokasi_bidang',
                'verbose_name': 'Lokasi Bidang',
                'verbose_name_plural': 'Lokasi Bidang',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nama_pegawai', models.CharField(db_column='nama_pegawai', max_length=200, verbose_name='Nama Pegawai')),
                ('nip', models.CharField(db_column='nip', max_length=60, verbose_name='NIP')),
                ('pangkat', models.CharField(db_column='pangkat', max_length=60, verbose_name='Pangkat')),
            ],
            options={
                'db_table': 'pegawai',
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('kode_provinsi', models.CharField(db_column='kode_provinsi', max_length=20, verbose_name='Kode Provinsi')),
                ('nama_provinsi', models.CharField(db_column='nama_provinsi', max_length=200, verbose_name='Nama Provinsi')),
            ],
            options={
                'db_table': 'provinsi',
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.CreateModel(
            name='SKPD',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('kode_skpd', models.CharField(db_column='kode_skpd', max_length=20, verbose_name='Kode SKPD')),
                ('nama_skpd', models.CharField(db_column='nama_skpd', max_length=200, verbose_name='Nama SKPD')),
                ('id_lokasi_bidang', models.ForeignKey(db_column='id_lokasi_bidang', on_delete=django.db.models.deletion.CASCADE, to='sppd.LokasiBidang', verbose_name='Lokasi Bidang')),
            ],
            options={
                'db_table': 'skpd',
                'verbose_name': 'SKPD',
                'verbose_name_plural': 'SKPD',
            },
        ),
        migrations.CreateModel(
            name='SPPD',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='No Urut')),
                ('no_sppd', models.CharField(db_column='no_sppd', max_length=60, verbose_name='No SPPD')),
                ('tanggal_berangkat', models.DateField(db_column='tanggal_berangkat', verbose_name='Tanggal Berangkat')),
                ('tanggal_kembali', models.DateField(db_column='tanggal_kembali', verbose_name='Tanggal Kembali')),
                ('keterangan', models.CharField(db_column='keterangan', max_length=200, verbose_name='Keterangan')),
                ('id_pegawai', models.ForeignKey(db_column='id_pegawai', on_delete=django.db.models.deletion.CASCADE, to='sppd.Pegawai', verbose_name='Pegawai')),
                ('id_skpd', models.ForeignKey(db_column='id_skpd', on_delete=django.db.models.deletion.CASCADE, to='sppd.SKPD', verbose_name='SKPD')),
            ],
            options={
                'db_table': 'sppd',
                'verbose_name': 'SPPD',
                'verbose_name_plural': 'SPPD',
            },
        ),
        migrations.CreateModel(
            name='StatusPegawai',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status_pegawai', models.CharField(db_column='status_pegawai', max_length=40, unique=True, verbose_name='Status Pegawai')),
            ],
            options={
                'db_table': 'status_pegawai',
                'verbose_name': 'Status Pegawai',
                'verbose_name_plural': 'Status Pegawai',
            },
        ),
        migrations.AddField(
            model_name='pegawai',
            name='id_skpd',
            field=models.ForeignKey(db_column='id_skpd', on_delete=django.db.models.deletion.CASCADE, to='sppd.SKPD', verbose_name='SKPD'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='id_status_pegawai',
            field=models.ForeignKey(db_column='id_status_pegawai', on_delete=django.db.models.deletion.CASCADE, to='sppd.StatusPegawai', verbose_name='Status Pegawai'),
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='id_provinsi',
            field=models.ForeignKey(db_column='id_provinsi', on_delete=django.db.models.deletion.CASCADE, to='sppd.Provinsi', verbose_name='Provinsi'),
        ),
    ]
