# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-31 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppd',
            name='dibayar',
            field=models.DecimalField(db_column='dibayar', decimal_places=0, default=0, max_digits=15, verbose_name='Dibayar (Rp)'),
        ),
    ]
