# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nama_kabupaten', models.CharField(db_column='nama_kabupaten', max_length=200, verbose_name='Nama Kabupaten')),
            ],
            options={
                'db_table': 'kabupaten',
                'verbose_name': 'Kabupaten',
                'verbose_name_plural': 'Kabupaten',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nama_provinsi', models.CharField(db_column='nama_provinsi', max_length=200, verbose_name='Nama Provinsi')),
            ],
            options={
                'db_table': 'provinsi',
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='id_provinsi',
            field=models.ForeignKey(db_column='id_provinsi', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Provinsi', verbose_name='Provinsi'),
        ),
    ]
