# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabupaten',
            name='nama_kabupaten',
            field=models.CharField(db_column='nama_kabupaten', max_length=200, verbose_name='Kabupaten'),
        ),
        migrations.AlterField(
            model_name='provinsi',
            name='nama_provinsi',
            field=models.CharField(db_column='nama_provinsi', max_length=200, verbose_name='Provinsi'),
        ),
    ]
