# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0003_kecamatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kecamatan',
            name='id_provinsi',
        ),
        migrations.DeleteModel(
            name='Kecamatan',
        ),
    ]
