# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0005_kecamatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nama_desa', models.CharField(db_column='nama_desa', max_length=200, verbose_name='Desa')),
                ('id_kecamatan', models.ForeignKey(db_column='id_kecamatan', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'db_table': 'desa',
                'verbose_name': 'Desa',
                'verbose_name_plural': 'Desa',
            },
        ),
    ]
