# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0006_desa'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKelamin',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('kode_jenis_kelamin', models.CharField(db_column='kode_jenis_kelamin', max_length=3, verbose_name='Kode Jenis Kelamin')),
                ('jenis_kelamin', models.CharField(db_column='jenis_kelamin', max_length=40, verbose_name='Jenis Kelamin')),
            ],
            options={
                'db_table': 'jenis_kelamin',
                'verbose_name': 'Jenis Kelamin',
                'verbose_name_plural': 'Jenis Kelamin',
            },
        ),
        migrations.CreateModel(
            name='RT',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rt', models.CharField(db_column='rt', max_length=5, verbose_name='RT')),
            ],
            options={
                'db_table': 'rt',
                'verbose_name': 'RT',
                'verbose_name_plural': 'RT',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=40, verbose_name='Status')),
            ],
            options={
                'db_table': 'status',
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
    ]
