# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0007_jeniskelamin_rt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('no_ktp', models.DecimalField(db_column='no_ktp', decimal_places=0, max_digits=16, validators=[django.core.validators.MinLengthValidator(16, message='Cek No. KTP')], verbose_name='No KTP')),
                ('nama', models.CharField(db_column='nama', max_length=200, verbose_name='Nama')),
                ('id_desa', models.ForeignKey(db_column='id_desa', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Desa', verbose_name='Desa')),
            ],
            options={
                'db_table': 'penduduk',
                'verbose_name': 'Penduduk',
                'verbose_name_plural': 'Penduduk',
            },
        ),
    ]
