# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0008_penduduk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='no_ktp',
            field=models.DecimalField(db_column='no_ktp', decimal_places=0, max_digits=16, verbose_name='No KTP'),
        ),
    ]
