# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0012_auto_20170828_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='no_ktp',
            field=models.CharField(db_column='no_ktp', max_length=16, validators=[django.core.validators.MinLengthValidator(16, message='No KTP Kurang')], verbose_name='No KTP'),
        ),
    ]
