# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0015_auto_20170828_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='no_ktp',
            field=models.CharField(db_column='no_ktp', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16, message='No KTP Kurang'), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Cek No KTP')], verbose_name='No KTP'),
        ),
    ]
