# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0016_auto_20170828_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penduduk',
            name='id_desa',
        ),
        migrations.DeleteModel(
            name='Penduduk',
        ),
    ]
