# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0017_auto_20170830_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('no_ktp', models.CharField(db_column='no_ktp', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16, message='No KTP Kurang'), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Cek No KTP')], verbose_name='No KTP')),
                ('nama', models.CharField(db_column='nama', max_length=200, verbose_name='Nama')),
                ('tempat_lahir', models.CharField(db_column='tempat_lahir', max_length=200, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(db_column='tanggal_lahir', verbose_name='Tanggal Lahir')),
                ('no_rumah', models.CharField(blank=True, db_column='no_rumah', max_length=10, null=True, verbose_name='No Rumah')),
                ('bantuan', models.DecimalField(db_column='bantuan', decimal_places=0, default=0, max_digits=15, verbose_name='Bantuan')),
                ('keterangan', models.TextField(blank=True, db_column='keterangan', null=True, verbose_name='Keterangan')),
                ('id_desa', models.ForeignKey(db_column='id_desa', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Desa', verbose_name='Desa')),
                ('id_jenis_kelamin', models.ForeignKey(db_column='id_jenis_kelamin', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.JenisKelamin', verbose_name='Jenis Kelamin')),
                ('id_rt', models.ForeignKey(db_column='id_rt', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.RT', verbose_name='RT')),
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Status', verbose_name='Status')),
            ],
            options={
                'db_table': 'penduduk',
                'verbose_name': 'Penduduk',
                'verbose_name_plural': 'Penduduk',
            },
        ),
    ]
