# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0019_auto_20170830_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='id_jenis_kelamin',
            field=models.ForeignKey(db_column='id_jenis_kelamin', default=1, on_delete=django.db.models.deletion.CASCADE, to='kabupaten.JenisKelamin', verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', default=1, on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Status', verbose_name='Status'),
        ),
    ]
