# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0020_auto_20170830_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='bantuan',
            field=models.BigIntegerField(db_column='bantuan', default=0, verbose_name='Bantuan'),
        ),
    ]
