# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabupaten', '0022_auto_20170830_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendudukPenerima',
            fields=[
            ],
            options={
                'verbose_name': 'Penduduk Penerima',
                'proxy': True,
                'verbose_name_plural': 'Penduduk Penerima',
                'indexes': [],
            },
            bases=('kabupaten.penduduk',),
        ),
    ]
